name: ArchiveLocale
version: '1.0-SNAPSHOT'
main: com.github.thelampgod.archiveLocale.ArchiveLocale
api-version: '1.21'
authors: [ thelampgod ]
description: Adds localization to The Archive minecraft server
website: https://github.com/thearchive-world/ArchiveLocale
depend: [ ProtocolLib ]

commands:
  SetLocale:
    description: Sets the locale to use
    usage: /SetLocale <locale>
